### PR TITLE
done

### PR DESCRIPTION
**Pull request by spiritbro1**
hello this is a fix for issue https://github.com/Jazzepi/bunny-tracker/issues/10,

work done,

please review if it's good i will open pull request

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#10: e2e spectron tests click on navbar buttons with no effect](https://issuehunt.io/repos/187306668/issues/10)
---
</details>

### CODE REVIEW

**Comment by Jazzepi** [comment]
I'll take a look tonight!

**Comment by spiritbro1** [comment]
thank you sir will wait for your review i hope it's good

**Comment by Jazzepi** [comment]
I cherry picked this and ran it. Tests failing.

image

**Comment by spiritbro1** [comment]
are you using npm install or yarn install? and can you show me your nodejs version? im using nodejs version 14 maybe i can try it using your setting

**Comment by spiritbro1** [comment]
image
it works on me this is how i run it:

- first clone my branch https://github.com/spiritbro1/bunny-tracker
- run npm install
- run npm run e2e:full 
please try again

**Comment by spiritbro1** [comment]
@Jazzepi i add the timeout please pull again from my repo then run again

**Comment by Jazzepi** [comment]
@spiritbro1 Looks good! Go ahead and submit your pull request in issue hunt.

**Comment by spiritbro1** [comment]
image
done sir, you can merge it now

**Review by Jazzepi — APPROVED** [review]

**Pull request merged**
